---
title: L’instruction 'Throw' ne peut pas omettre l’opérande en dehors d’une instruction 'Catch' ou dans une instruction 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 05fc14b0f493b3901fda9fbdba7e0fcebae6bea5
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 09/23/2020
ms.locfileid: "91068893"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a><span data-ttu-id="9a2c8-102">L’instruction 'Throw' ne peut pas omettre l’opérande en dehors d’une instruction 'Catch' ou dans une instruction 'Finally'</span><span class="sxs-lookup"><span data-stu-id="9a2c8-102">'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement</span></span>

<span data-ttu-id="9a2c8-103">Les instructions`Throw` situées en dehors de l’instruction `Catch` doivent fournir le nom d’un objet exception.</span><span class="sxs-lookup"><span data-stu-id="9a2c8-103">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="9a2c8-104">**ID d’erreur :** BC30666</span><span class="sxs-lookup"><span data-stu-id="9a2c8-104">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="9a2c8-105">Pour corriger cette erreur</span><span class="sxs-lookup"><span data-stu-id="9a2c8-105">To correct this error</span></span>  
  
1. <span data-ttu-id="9a2c8-106">Spécifiez le nom d’un objet d’exception dérivé de `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="9a2c8-106">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2. <span data-ttu-id="9a2c8-107">Restructurez votre code pour que l’instruction `Throw` se trouve dans un bloc `Catch` .</span><span class="sxs-lookup"><span data-stu-id="9a2c8-107">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="9a2c8-108">Voir aussi</span><span class="sxs-lookup"><span data-stu-id="9a2c8-108">See also</span></span>

- [<span data-ttu-id="9a2c8-109">Throw, instruction</span><span class="sxs-lookup"><span data-stu-id="9a2c8-109">Throw Statement</span></span>](../language-reference/statements/throw-statement.md)
- [<span data-ttu-id="9a2c8-110">Try...Catch...Finally (instruction)</span><span class="sxs-lookup"><span data-stu-id="9a2c8-110">Try...Catch...Finally Statement</span></span>](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [<span data-ttu-id="9a2c8-111">Gestion et levée d’exceptions dans .NET</span><span class="sxs-lookup"><span data-stu-id="9a2c8-111">Handling and throwing exceptions in .NET</span></span>](../../standard/exceptions/index.md)
